export{default as Home } from "./home"
export{default as Login} from "./login"
export{default as SignUp} from "./SignUp"
export{default as ActiveGame} from "./ActiveGame"
export{default as GameLog} from "./gameLog"
export{default as History} from "./history"